<script setup>
import { onMounted, ref, watch } from 'vue'
import { Bookmark, Trash2 } from 'lucide-vue-next'
import { api } from '../../services/api'
const types=['predictions','builders','slips'],active=ref('predictions'),items=ref([]),loading=ref(false),error=ref('')
const load=async()=>{loading.value=true;error.value='';try{items.value=(await api.savedList(active.value)).items}catch(failure){error.value=failure.message}finally{loading.value=false}}
const remove=async item=>{await api.savedDelete(active.value,item.id);items.value=items.value.filter(candidate=>candidate.id!==item.id)}
watch(active,load);onMounted(load)
const title=item=>item.selection||item.name||`${item.provider||'Saved'} slip`
const detail=item=>item.predictionType||item.buildStyle||`${item.selections?.length||0} selections`
</script>
<template><div class="saved-page"><header><span class="eyebrow">NINTH / USER-OWNED DATA</span><h1>Saved intelligence.</h1><p>Private predictions, generated cards and imported slips. Every query is scoped to your authenticated user ID at the database.</p></header><nav><button v-for="type in types" :key="type" :class="{active:active===type}" @click="active=type">{{type}}</button></nav><p v-if="error" class="saved-error">{{error}}</p><div v-if="loading" class="saved-empty">LOADING PRIVATE RECORDS…</div><div v-else-if="!items.length" class="saved-empty"><Bookmark/><b>No saved {{active}} yet.</b><p>Items saved from authenticated NINTH tools will appear here.</p></div><section v-else><article v-for="item in items" :key="item.id"><span>{{item.sport||item.provider||'NINTH'}}</span><div><b>{{title(item)}}</b><p>{{detail(item)}} · {{new Date(item.createdAt).toLocaleString()}}</p></div><button type="button" aria-label="Delete saved item" @click="remove(item)"><Trash2/></button></article></section></div></template>
<style scoped>.saved-page{padding-top:28px}.saved-page>header{padding:58px 0 44px;border-bottom:1px solid var(--line)}h1{margin:18px 0 12px;font-size:clamp(4rem,9vw,8rem);letter-spacing:-.08em;line-height:.85}.saved-page>header p{max-width:720px;color:var(--muted);font-size:15px;line-height:1.65}.saved-page>nav{height:66px;display:flex;border-bottom:1px solid var(--line)}nav button{min-width:140px;border:0;border-right:1px solid var(--line);background:transparent;color:var(--muted);font:600 11px 'DM Mono';text-transform:uppercase}.saved-page nav button.active{background:var(--contrast);color:var(--accent)}section{display:grid;padding:28px 0}article{min-height:86px;padding:15px 18px;display:grid;grid-template-columns:100px 1fr 46px;align-items:center;gap:18px;border:1px solid var(--line);border-bottom:0;background:var(--surface)}article:last-child{border-bottom:1px solid var(--line)}article>span{color:var(--accent);font:600 10px 'DM Mono';text-transform:uppercase}article div{display:grid;gap:5px}article b{font-size:15px}article p{margin:0;color:var(--muted);font:500 11px 'DM Mono'}article button{width:42px;height:42px;padding:0;display:grid;place-items:center;border:1px solid var(--line);background:transparent;color:var(--red)}article button svg{width:17px}.saved-empty{min-height:270px;display:grid;place-items:center;align-content:center;gap:10px;color:var(--muted);font:600 11px 'DM Mono';text-align:center}.saved-empty svg{width:30px;color:var(--accent)}.saved-empty b{color:var(--text);font-size:16px}.saved-empty p{margin:0;font-size:12px}.saved-error{padding:14px;color:var(--red)}@media(max-width:600px){.saved-page>header{padding:38px 0}.saved-page>nav{overflow:auto}nav button{min-width:112px}article{grid-template-columns:1fr 44px}article>span{grid-column:1/3}article p{line-height:1.5}}</style>
