<script setup>
import { computed, reactive, ref } from 'vue'
import { CheckCircle2, Eye, EyeOff } from 'lucide-vue-next'
import { useRoute } from 'vue-router'
import AuthShell from '../components/AuthShell.vue'
import { api } from '../../../services/api'
const route=useRoute(),form=reactive({password:'',passwordConfirmation:''}),loading=ref(false),error=ref(''),fields=ref({}),complete=ref(false),show=ref(false)
const token=computed(()=>String(route.query.token||''))
const submit=async()=>{loading.value=true;error.value='';fields.value={};try{await api.authResetPassword({token:token.value,...form});complete.value=true}catch(failure){error.value=failure.message;fields.value=failure.fields||{}}finally{loading.value=false}}
</script>
<template><AuthShell eyebrow="NINTH / RESET PASSWORD" step="04" story-title="Rotate the key. Protect the record." story-copy="A completed reset invalidates other sessions so an old browser or stolen session cannot remain connected."><div class="auth-form"><div v-if="complete" class="auth-status"><div class="status-mark"><CheckCircle2/></div><h2>Password updated.</h2><p>Your existing sessions were closed. Sign in again with your new password.</p><RouterLink class="auth-submit" to="/auth/sign-in">Sign in securely</RouterLink></div><template v-else><header class="auth-form-head"><span>CHOOSE A NEW PASSWORD</span><h2>Make it strong and memorable.</h2><p>This link can be used once and expires automatically.</p></header><p v-if="!token" class="auth-error">This reset link is incomplete.</p><p v-if="error" class="auth-error">{{error}}</p><form @submit.prevent="submit"><label class="auth-field"><span>New password</span><div class="password-wrap"><input v-model="form.password" :type="show?'text':'password'" autocomplete="new-password" placeholder="At least 10 characters" :aria-invalid="Boolean(fields.password)" required><button type="button" @click="show=!show"><EyeOff v-if="show"/><Eye v-else/></button></div><small v-if="fields.password">{{fields.password}}</small></label><label class="auth-field"><span>Confirm password</span><input v-model="form.passwordConfirmation" :type="show?'text':'password'" autocomplete="new-password" placeholder="Repeat your new password" :aria-invalid="Boolean(fields.passwordConfirmation)" required><small v-if="fields.passwordConfirmation">{{fields.passwordConfirmation}}</small></label><button class="auth-submit" :disabled="loading||!token">{{loading?'Updating password…':'Update password'}}</button></form></template></div></AuthShell></template>
