<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { AlertTriangle, Check, LockKeyhole, Plus, RefreshCw, Sparkles, Trash2 } from 'lucide-vue-next'
import { AnimatePresence, LayoutGroup, motion, useReducedMotion } from 'motion-v'
import { useRoute, useRouter } from 'vue-router'
import SportIdentity from '../components/identity/SportIdentity.vue'
import CustomSelect from '../components/ui/CustomSelect.vue'
import UnifiedBuilderHero from '../components/builder/UnifiedBuilderHero.vue'
import UnifiedBuilderScore from '../components/builder/UnifiedBuilderScore.vue'
import { gamePrediction, probability, sentenceCase, sportLabel } from '../domain/sports'
import { sportById } from '../config/sports'
import { api } from '../services/api'
import { independentEventJointProbability } from '../domain/cardMath'

const props=defineProps({sport:{type:String,required:true}}),route=useRoute(),router=useRouter(),reduced=useReducedMotion()
const leagues=ref([]),games=ref([]),loading=ref(true),error=ref(''),selected=ref([]),target=ref(5),evidenceMode=ref('shadow'),marketMode=ref('all'),minimumProbability=ref('all'),minimumEdge=ref('all'),windowOffset=ref(0)
const active=computed(()=>sportById(props.sport)),competition=computed(()=>String(route.query.competition||'')),league=computed(()=>leagues.value.find(row=>String(row.id)===competition.value)||null)
const dateOnly=value=>new Date(`${String(value).slice(0,10)}T12:00:00`)
const activeWindow=computed(()=>{const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()+windowOffset.value*4);const end=new Date(start);end.setDate(end.getDate()+4);return{start,end,label:`${start.toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${new Date(end.getTime()-1).toLocaleDateString(undefined,{month:'short',day:'numeric'})}`}})
const activeGames=computed(()=>games.value.filter(game=>{const at=dateOnly(game.date||game.timestamp);return Number.isFinite(at.getTime())&&at>=activeWindow.value.start&&at<activeWindow.value.end}))
const allCandidates=computed(()=>activeGames.value.flatMap(game=>Object.entries(game.prediction?.markets||{}).filter(([,value])=>Number(value)>=.5).map(([market,value])=>({id:`${game.id}:${market}`,game,market,probability:Number(value),fairOdds:Number(game.prediction?.fair_odds?.[market])||null,marketOdds:Number(game.prediction?.prices?.[market])||null,noVig:Number(game.prediction?.no_vig_market_probability?.[market])||null,edge:Number.isFinite(Number(game.prediction?.edge?.[market]))?Number(game.prediction.edge[market]):null,eligible:game.prediction?.market_eligibility?.[market]===true,label:gamePrediction({...game,prediction:{...game.prediction,markets:{[market]:value}}})?.label||sentenceCase(market)}))).sort((a,b)=>Number(b.eligible)-Number(a.eligible)||b.probability-a.probability))
const marketKeys=computed(()=>[...new Set(allCandidates.value.map(row=>row.market))])
const candidates=computed(()=>allCandidates.value.filter(row=>marketMode.value==='all'||row.market===marketMode.value).filter(row=>evidenceMode.value==='production'?row.eligible:true).filter(row=>minimumProbability.value==='all'||row.probability>=Number(minimumProbability.value)).filter(row=>minimumEdge.value==='all'||(row.edge!=null&&row.edge>=Number(minimumEdge.value))))
const selectedIds=computed(()=>new Set(selected.value.map(row=>row.id))),occupied=computed(()=>new Set(selected.value.map(row=>String(row.game.id))))
const joint=computed(()=>independentEventJointProbability(selected.value)),average=computed(()=>selected.value.length?selected.value.reduce((sum,row)=>sum+row.probability,0)/selected.value.length:0)
const targetOptions=Array.from({length:9},(_,index)=>({value:index+2,label:`${index+2} legs`}))
const evidenceOptions=[{value:'shadow',label:'All forecasts',meta:'Model board'},{value:'production',label:'Builder eligible',meta:'Audited only'}]
const probabilityOptions=[{value:'all',label:'Any probability'},...[.55,.60,.65,.70].map(value=>({value:String(value),label:`${Math.round(value*100)}%+`}))]
const edgeOptions=[{value:'all',label:'Any / unavailable'},...[.02,.04,.06,.08].map(value=>({value:String(value),label:`${Math.round(value*100)}%+ edge`}))]
const competitionOptions=computed(()=>leagues.value.map(row=>({value:String(row.id),label:row.name,meta:row.code||row.discipline})))
const toggle=row=>{if(selectedIds.value.has(row.id)){selected.value=selected.value.filter(item=>item.id!==row.id);return}if(occupied.value.has(String(row.game.id))||selected.value.length>=Number(target.value))return;selected.value=[...selected.value,row]}
const buildBest=()=>{const rows=[],events=new Set(),directions=new Map(),directionCap=Math.max(2,Math.ceil(Number(target.value)/2));for(const row of candidates.value){const side=row.market.replace(/^(home|away|over|under).*/,'$1');if(events.has(String(row.game.id))||(directions.get(side)||0)>=directionCap)continue;rows.push(row);events.add(String(row.game.id));directions.set(side,(directions.get(side)||0)+1);if(rows.length>=Number(target.value))break}selected.value=rows}
const changeCompetition=value=>router.replace({query:{...route.query,competition:value,discipline:props.sport==='esports'?leagues.value.find(row=>String(row.id)===String(value))?.discipline:undefined}})
const load=async()=>{loading.value=true;error.value='';selected.value=[];try{const directory=await api.sportDirectory(props.sport,'leagues',{discipline:route.query.discipline});leagues.value=directory.items||[];const chosen=competition.value&&leagues.value.some(row=>String(row.id)===competition.value)?competition.value:String(leagues.value[0]?.id||'');if(chosen!==competition.value){changeCompetition(chosen);return}const result=await api.sportDirectory(props.sport,'games',{competition:chosen,discipline:league.value?.discipline||route.query.discipline,tournament:props.sport==='esports'?chosen:undefined});games.value=(result.items||[]).filter(game=>game.status!=='Completed')}catch(caught){error.value=caught?.message||'The competition builder could not be loaded.'}finally{loading.value=false}}
watch(()=>[props.sport,route.query.competition,route.query.discipline],load)
watch([evidenceMode,marketMode,target,minimumProbability,minimumEdge,windowOffset],()=>{selected.value=[]})
onMounted(load)
</script>

<template>
  <div class="unified-builder competition-builder" :style="{'--sport':active.accent}">
    <UnifiedBuilderHero :eyebrow="`${sportLabel(sport).toUpperCase()} / BUILDER`" :title="sport==='football'?'Build the match':'Build the series'" :accent="sport==='football'?'in context.':'from evidence.'" :description="sport==='football'?'Moneyline, draw, total-goals and both-teams-to-score distributions now use the same card-first hierarchy as MLB.':'Valorant, CS2 and League of Legends match-winner forecasts now use the same card-first hierarchy as MLB.'">
      <div class="builder-segment"><small>MODEL</small><div><button :class="{active:marketMode==='all'}" @click="marketMode='all'">ALL</button><button v-for="market in marketKeys.slice(0,5)" :key="market" :class="{active:marketMode===market}" @click="marketMode=market">{{sentenceCase(market).toUpperCase()}}</button></div></div>
      <div class="builder-control-bar"><CustomSelect :model-value="competition" label="Competition" :options="competitionOptions" searchable @update:model-value="changeCompetition"/><CustomSelect v-model="evidenceMode" label="Evidence" :options="evidenceOptions"/><CustomSelect v-model="marketMode" label="Market" :options="[{value:'all',label:'ALL MARKETS'},...marketKeys.map(value=>({value,label:sentenceCase(value)}))]"/><CustomSelect v-model="minimumProbability" label="Probability" :options="probabilityOptions"/><CustomSelect v-model="minimumEdge" label="Edge" :options="edgeOptions"/><CustomSelect v-model="target" label="Target legs" :options="targetOptions"/><button class="builder-refresh" :disabled="loading" @click="load"><RefreshCw :class="{spin:loading}"/> REFRESH</button></div>
    </UnifiedBuilderHero>
    <UnifiedBuilderScore :probability="joint" :selected="selected.length" :target="Number(target)" :average="average" :title="selected.length?`${selected.length}-leg ${league?.code||sportLabel(sport)} card`:'No legs selected'" description="The joint score multiplies probabilities only across different matches. One leg is permitted per match and Build Best caps repeated statistical directions." :detail="`${candidates.length} current signals from ${league?.name||'the selected competition'}. Builder eligibility is shown separately from model probability.`" fourth-label="EVIDENCE" :fourth-value="evidenceMode==='production'?'ELIGIBLE':'ALL'">
      <template #actions><button class="primary" :disabled="!candidates.length" @click="buildBest"><Sparkles/> BUILD BEST {{target}}</button><button :disabled="!selected.length" @click="selected=[]"><Trash2/> CLEAR</button></template>
    </UnifiedBuilderScore>
    <section class="builder-board-note"><span><i></i>{{activeGames.length}} {{sport==='esports'?'SERIES':'FIXTURES'}} · {{candidates.length}} FORECAST OUTCOMES · {{activeWindow.label}}</span><div class="window-nav"><button @click="windowOffset--">← PREVIOUS</button><button :disabled="windowOffset===0" @click="windowOffset=0">CURRENT</button><button @click="windowOffset++">NEXT →</button></div><p>Only exact-event forecasts inside this four-day window appear. The evidence filter never changes the underlying probabilities.</p></section>
    <div v-if="selected.length" class="builder-selected-summary"><AnimatePresence mode="popLayout"><motion.article v-for="(row,index) in selected" :key="row.id" layout :initial="reduced?false:{opacity:0,y:10}" :animate="{opacity:1,y:0}" :exit="reduced?undefined:{opacity:0,scale:.97}"><span>{{String(index+1).padStart(2,'0')}}</span><div><small>{{sentenceCase(row.market)}} · {{probability(row.probability)}}</small><b>{{row.label}}</b><em>{{row.game.away?.name}} @ {{row.game.home?.name}}</em></div><button @click="toggle(row)">×</button></motion.article></AnimatePresence></div>
    <section class="builder-day"><header><div><span class="eyebrow">{{league?.name||'CURRENT COMPETITION'}}</span><h2>{{candidates.length}} source-backed outcomes</h2></div><small>{{activeGames.length}} ACTIVE EVENTS</small></header>
      <div v-if="loading" class="builder-state"><RefreshCw class="spin"/><b>Loading competition evidence</b><p>Joining the exact fixture IDs to their latest immutable model export.</p></div>
      <div v-else-if="error" class="builder-state"><AlertTriangle/><b>Builder unavailable</b><p>{{error}}</p></div>
      <div v-else-if="!candidates.length" class="builder-state"><LockKeyhole/><b>No forecast export matches these controls</b><p>Fixtures remain visible elsewhere; this builder does not manufacture selections from standings.</p></div>
      <LayoutGroup v-else :id="`${sport}-builder`"><motion.div layout class="builder-card-grid"><AnimatePresence mode="popLayout"><motion.article v-for="row in candidates" :key="row.id" layout class="builder-choice-card" :class="{selected:selectedIds.has(row.id)}" :initial="reduced?false:{opacity:0,y:12}" :animate="{opacity:1,y:0}" :exit="reduced?undefined:{opacity:0,scale:.98}" :while-hover="reduced?undefined:{y:-2}">
        <div class="builder-card-meta"><span>{{row.game.date}} · {{row.game.time}}</span><strong>{{row.eligible?'BUILDER ELIGIBLE':'MODEL FORECAST'}}</strong></div>
        <div class="builder-matchup"><div class="builder-team"><SportIdentity :identity="row.game.away" :size="38"/><span><small>{{sport==='esports'?'SIDE A':'AWAY'}}</small><b>{{row.game.away?.name}}</b></span></div><i class="builder-versus">{{sport==='esports'?'VS':'AT'}}</i><div class="builder-team home"><SportIdentity :identity="row.game.home" :size="38"/><span><small>{{sport==='esports'?'SIDE B':'HOME'}}</small><b>{{row.game.home?.name}}</b></span></div></div>
        <div class="builder-market-label">{{sentenceCase(row.market)}}<span>{{league?.code||sportLabel(sport)}}</span></div>
        <button class="builder-selection" :class="{active:selectedIds.has(row.id)}" :disabled="!selectedIds.has(row.id)&&(occupied.has(String(row.game.id))||selected.length>=Number(target))" @click="toggle(row)"><span><small>{{row.marketOdds?`MARKET @ ${row.marketOdds.toFixed(3)}`:row.fairOdds?`MODEL FAIR @ ${row.fairOdds.toFixed(3)}`:'PRICE UNAVAILABLE'}}</small><b>{{row.label}}</b></span><strong>{{probability(row.probability)}}</strong><Check v-if="selectedIds.has(row.id)"/><Plus v-else/></button>
        <footer class="builder-card-footer"><span>{{row.edge==null?'NO MATCHED PRICE / NO EDGE':`NO-VIG ${probability(row.noVig)} · EDGE ${row.edge>=0?'+':''}${probability(row.edge)}`}}</span><b>ONE PICK PER EVENT</b></footer>
      </motion.article></AnimatePresence></motion.div></LayoutGroup>
    </section>
  </div>
</template>

<style scoped>.competition-builder{padding-top:20px}.builder-segment>div{grid-auto-flow:row;grid-template-columns:repeat(3,minmax(0,1fr))}.builder-segment button{min-height:42px}.builder-control-bar{grid-template-columns:repeat(3,minmax(0,1fr))}.builder-refresh{grid-column:1/-1}.builder-control-bar :deep(.custom-select){min-width:0}.window-nav{display:flex;gap:5px}.window-nav button{min-height:34px;padding:0 10px;border:1px solid var(--line);background:var(--surface);color:var(--text);font:700 8px 'DM Mono';cursor:pointer}.window-nav button:disabled{opacity:.35}.builder-board-note{grid-template-columns:1fr auto}.builder-board-note p{grid-column:1/-1}@media(max-width:850px){.builder-control-bar{grid-template-columns:1fr 1fr}.builder-segment>div{grid-template-columns:repeat(2,1fr)}.builder-segment button:first-child{grid-column:1/-1}.builder-board-note{grid-template-columns:1fr}.window-nav{grid-row:2}.builder-board-note p{grid-column:1}}@media(max-width:500px){.builder-control-bar{grid-template-columns:1fr}.window-nav button{flex:1}}</style>
