<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../services/api'
import TeamLogo from '../components/team/TeamLogo.vue'
import LoadError from '../components/ui/LoadError.vue'

const teams=ref([]),loading=ref(true),error=ref(''),scope=ref('overall')
const scopes=[['overall','Overall'],['al','American League'],['nl','National League'],['divisions','By division']]
const load=async()=>{loading.value=true;error.value='';try{teams.value=await api.teams()}catch(caught){error.value=caught?.message||'Official standings could not be loaded.'}finally{loading.value=false}}
onMounted(load)
const ranked=computed(()=>{const values=[...teams.value].filter(team=>scope.value==='al'?team.league==='American League':scope.value==='nl'?team.league==='National League':true).sort((a,b)=>Number(b.pct)-Number(a.pct)||b.run_differential-a.run_differential);const leader=values[0];return values.map((team,index)=>({...team,games_back:index?((((Number(leader.wins)-Number(team.wins))+(Number(team.losses)-Number(leader.losses)))/2)||'—'):'—'}))})
const divisions=computed(()=>Object.entries(teams.value.reduce((groups,team)=>{(groups[team.division]??=[]).push(team);return groups},{})).sort(([a],[b])=>a.localeCompare(b)).map(([name,items])=>[name,[...items].sort((a,b)=>Number(b.pct)-Number(a.pct))]))
</script>
<template><div class="standings-page"><section class="standings-hero"><span class="eyebrow">NINTH / OFFICIAL MLB TABLE</span><h1>The shape<br>of the league.</h1><p>Overall, league, and divisional standings from the current MLB record feed. Ties are ordered by run differential for display only.</p></section><nav class="scope-tabs" aria-label="Standings scope"><button v-for="item in scopes" :key="item[0]" :class="{active:scope===item[0]}" @click="scope=item[0]">{{item[1]}}</button></nav><div v-if="loading" class="state">LOADING OFFICIAL STANDINGS…</div><template v-else-if="scope!=='divisions'"><section class="table-panel"><header><div><span class="eyebrow">{{scopes.find(item=>item[0]===scope)?.[1]}}</span><h2>2026 standings</h2></div><small>{{ranked.length}} CLUBS · MLB STATSAPI</small></header><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Club</th><th>W</th><th>L</th><th>PCT</th><th>GB</th><th>Last 10</th><th>Streak</th><th>Run diff</th></tr></thead><tbody><tr v-for="(team,index) in ranked" :key="team.id"><td class="rank mono">{{String(index+1).padStart(2,'0')}}</td><td><RouterLink :to="`/teams/${team.id}`"><TeamLogo :team="team" :size="34"/><span><b>{{team.name}}</b><small>{{team.division}}</small></span></RouterLink></td><td class="mono">{{team.wins}}</td><td class="mono">{{team.losses}}</td><td class="mono"><b>{{team.pct}}</b></td><td class="mono">{{team.games_back||'—'}}</td><td class="mono">{{team.last_ten?.wins||0}}–{{team.last_ten?.losses||0}}</td><td class="mono">{{team.streak||'—'}}</td><td class="mono" :class="team.run_differential>=0?'positive':'negative'">{{team.run_differential>=0?'+':''}}{{team.run_differential}}</td></tr></tbody></table></div></section></template><div v-else class="division-grid"><section v-for="division in divisions" :key="division[0]" class="division-card"><header><span class="eyebrow">{{division[0].startsWith('American')?'AL':'NL'}}</span><h2>{{division[0].replace('American League ','').replace('National League ','')}}</h2></header><RouterLink v-for="(team,index) in division[1]" :key="team.id" :to="`/teams/${team.id}`"><span class="mono">{{index+1}}</span><TeamLogo :team="team" :size="34"/><div><b>{{team.name}}</b><small>{{team.wins}}–{{team.losses}} · {{team.streak||'—'}}</small></div><strong class="mono">{{team.pct}}</strong><em class="mono">{{team.games_back||'—'}} GB</em></RouterLink></section></div></div></template>
<style scoped>
.standings-page{display:grid;gap:0}.standings-hero{min-height:350px;padding:55px 0;display:flex;flex-direction:column;justify-content:center;border-bottom:1px solid var(--line)}h1{font-size:clamp(58px,7vw,96px);line-height:.82;letter-spacing:-.085em;margin:18px 0 25px}.standings-hero p{max-width:650px;font-size:12px;line-height:1.7;color:var(--muted)}.scope-tabs{display:flex!important;margin:0!important;padding:18px 0!important;gap:7px!important;border-bottom:1px solid var(--line)}.scope-tabs button{padding:11px 15px;border:1px solid var(--line);background:var(--surface);font:600 8px 'DM Mono';cursor:pointer}.scope-tabs button.active{background:var(--ink);color:var(--accent);border-color:var(--ink)}.table-panel{margin:28px 0;border:1px solid var(--line);background:var(--surface)}.table-panel>header,.division-card>header{display:flex;align-items:end;justify-content:space-between;padding:18px;border-bottom:1px solid var(--line)}h2{font-size:18px;margin:6px 0 0}.table-panel>header small{font:500 7px 'DM Mono';color:var(--muted)}table{width:100%;border-collapse:collapse}th{text-align:left;padding:11px;font:500 7px 'DM Mono';color:var(--muted);border-bottom:1px solid var(--line)}td{padding:9px 11px;border-bottom:1px solid var(--line);font-size:9px}tbody tr:hover{background:var(--wash)}td a{display:flex;align-items:center;gap:10px;text-decoration:none;min-width:220px}td a span{display:flex;flex-direction:column}td a b{font-size:10px}td a small{margin-top:3px;font-size:7px;color:var(--muted)}td.rank{color:var(--muted)}.positive{color:#568900}.negative{color:#d95436}.division-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px;padding:28px 0}.division-card{border:1px solid var(--line);background:var(--surface)}.division-card>a{display:grid;grid-template-columns:20px 42px 1fr auto 48px;align-items:center;gap:8px;padding:10px 13px;border-bottom:1px solid var(--line);text-decoration:none}.division-card>a:hover{background:var(--wash)}.division-card>a>span,.division-card em{font-size:8px;color:var(--muted);font-style:normal}.division-card>a div{display:flex;flex-direction:column}.division-card>a div b{font-size:10px}.division-card>a div small{font-size:7px;color:var(--muted);margin-top:3px}.division-card>a strong{font-size:9px}.state{padding:90px;text-align:center;font:9px 'DM Mono'}
@media(max-width:800px){.division-grid{grid-template-columns:1fr}.scope-tabs{overflow-x:auto}.scope-tabs button{flex:none}.standings-hero{min-height:300px;padding:35px 0}.table-wrap{overflow-x:auto}table{min-width:850px}}
</style>
