<script setup>
import {computed,onMounted,ref} from 'vue'
import {Search,ArrowUpRight} from 'lucide-vue-next'
import {api} from '../services/api'
import TeamLogo from '../components/team/TeamLogo.vue'
import LoadingState from '../components/ui/LoadingState.vue'
const teams=ref([]),query=ref(''),league=ref('all'),loading=ref(true),error=ref('')
const load=async()=>{loading.value=true;error.value='';try{teams.value=await api.teams()}catch(caught){error.value=caught?.message||'The team directory could not be loaded.'}finally{loading.value=false}}
onMounted(load)
const filtered=computed(()=>teams.value.filter(team=>(league.value==='all'||team.league?.startsWith(league.value))&&(!query.value||`${team.name} ${team.abbr} ${team.division}`.toLowerCase().includes(query.value.toLowerCase()))).sort((a,b)=>a.name.localeCompare(b.name)))
const leaders=computed(()=>[...teams.value].sort((a,b)=>Number(b.pct)-Number(a.pct)).slice(0,3))
</script>
<template><div class="directory"><section class="directory-head"><div><span class="eyebrow">30 CLUBS / ONE LEAGUE</span><h1>Find your team.</h1><p>Every MLB club, with live records, form, rosters, and the context behind the next game.</p></div><div class="leaders"><small>LEAGUE PACE</small><RouterLink v-for="(team,index) in leaders" :key="team.id" :to="`/teams/${team.id}`"><span class="mono">0{{index+1}}</span><TeamLogo :team="team" :size="32"/><b>{{team.abbr}}</b><em>{{team.pct}}</em></RouterLink></div></section><section class="directory-tools"><label><Search :size="17"/><input v-model="query" placeholder="Search clubs, cities, or divisions"></label><div class="segmented"><button v-for="item in [['all','All'],['American','AL'],['National','NL']]" :key="item[0]" :class="{active:league===item[0]}" @click="league=item[0]">{{item[1]}}</button></div><span class="mono">{{filtered.length}} CLUBS</span></section><LoadingState v-if="loading" label="Loading all 30 clubs" detail="Synchronizing records, divisions and current form."/><section v-else class="team-grid"><RouterLink v-for="team in filtered" :key="team.id" :to="`/teams/${team.id}`" class="team-card"><div class="team-mark"><TeamLogo :team="team" :size="74"/><ArrowUpRight :size="18"/></div><span class="eyebrow">{{team.division}}</span><h2>{{team.name}}</h2><div class="record"><strong class="mono">{{team.wins}}–{{team.losses}}</strong><span><b>{{team.pct}}</b> PCT</span></div><footer><span>{{team.streak||'—'}} CURRENT</span><span :class="team.run_differential>=0?'positive':'negative'">{{team.run_differential>=0?'+':''}}{{team.run_differential}} RUN DIFF</span></footer></RouterLink></section></div></template>
<style scoped>.directory{display:grid;gap:22px}.directory-head{display:grid;grid-template-columns:1.3fr .7fr;gap:40px;align-items:end;padding:35px 0 10px;border-bottom:1px solid var(--line)}h1{font-size:clamp(42px,6vw,82px);line-height:.95;letter-spacing:-.075em;margin:13px 0 18px}p{max-width:600px;color:var(--muted);font-size:13px;line-height:1.7}.leaders{display:grid;gap:7px}.leaders>small{font:600 8px 'DM Mono';color:var(--muted);margin-bottom:4px}.leaders a{display:grid;grid-template-columns:24px 34px 1fr auto;align-items:center;gap:9px;text-decoration:none;padding:8px 0;border-top:1px solid var(--line)}.leaders a span{font-size:8px;color:var(--muted)}.leaders a b{font-size:11px}.leaders a em{font:500 10px 'DM Mono';font-style:normal;color:var(--accent)}.directory-tools{display:flex;align-items:center;gap:12px}.directory-tools label{height:44px;flex:1;max-width:520px;display:flex;align-items:center;gap:9px;padding:0 14px;border:1px solid var(--line);border-radius:3px;background:var(--surface)}.directory-tools input{width:100%;border:0;outline:0;background:transparent;color:var(--text);font-size:11px}.segmented{display:flex;border:1px solid var(--line);padding:3px}.segmented button{border:0;background:transparent;padding:8px 13px;font:600 9px 'DM Mono';color:var(--muted);cursor:pointer}.segmented button.active{background:var(--ink);color:var(--paper)}.directory-tools>span{margin-left:auto;font-size:9px;color:var(--muted)}.team-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.team-card{min-width:0;padding:22px;border:1px solid var(--line);background:var(--surface);text-decoration:none;transition:.2s}.team-card:hover{background:var(--ink);color:var(--paper);transform:translateY(-3px)}.team-card:hover .eyebrow,.team-card:hover footer{color:#9ca09a}.team-mark{height:85px;display:flex;justify-content:space-between;align-items:flex-start}.team-card h2{font-size:20px;letter-spacing:-.035em;margin:8px 0 24px}.record{display:flex;align-items:end;justify-content:space-between}.record strong{font-size:28px;letter-spacing:-.07em}.record span{display:flex;flex-direction:column;text-align:right;font:600 7px 'DM Mono';color:var(--muted)}.record span b{font-size:11px;color:var(--text)}.team-card:hover .record span b{color:var(--paper)}footer{display:flex;justify-content:space-between;margin-top:17px;padding-top:12px;border-top:1px solid var(--line);font:600 7px 'DM Mono';color:var(--muted)}.positive{color:var(--green)}.negative{color:var(--orange)}.state{padding:70px;text-align:center;font:10px 'DM Mono';color:var(--muted)}@media(max-width:950px){.team-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.directory-head{grid-template-columns:1fr;padding-top:20px}.leaders{display:none}.directory-tools{flex-wrap:wrap}.directory-tools label{max-width:none;width:100%;flex-basis:100%}.directory-tools>span{margin-left:auto}.team-grid{grid-template-columns:1fr}.team-card{padding:18px}}</style>
