<script setup>
import{computed,nextTick,onBeforeUnmount,onMounted,ref}from'vue';import{Check,ChevronDown,Search}from'lucide-vue-next'
const props=defineProps({modelValue:[String,Number],options:{type:Array,default:()=>[]},placeholder:{type:String,default:'Select'},searchable:Boolean,label:String});const emit=defineEmits(['update:modelValue','change'])
const root=ref(),searchInput=ref(),open=ref(false),query=ref(''),active=ref(0)
const selected=computed(()=>props.options.find(option=>String(option.value)===String(props.modelValue)))
const filtered=computed(()=>{const term=query.value.toLowerCase().trim();return term?props.options.filter(option=>`${option.label} ${option.meta||''}`.toLowerCase().includes(term)):props.options})
const toggle=async()=>{open.value=!open.value;active.value=Math.max(0,filtered.value.findIndex(option=>String(option.value)===String(props.modelValue)));if(open.value&&props.searchable)await nextTick(()=>searchInput.value?.focus())}
const choose=option=>{emit('update:modelValue',option.value);emit('change',option.value);open.value=false;query.value=''}
const keydown=event=>{if(!open.value&&['ArrowDown','Enter',' '].includes(event.key)){event.preventDefault();toggle();return}if(!open.value)return;if(event.key==='Escape'){open.value=false;return}if(event.key==='ArrowDown'){event.preventDefault();active.value=Math.min(filtered.value.length-1,active.value+1)}if(event.key==='ArrowUp'){event.preventDefault();active.value=Math.max(0,active.value-1)}if(event.key==='Enter'&&filtered.value[active.value]){event.preventDefault();choose(filtered.value[active.value])}}
const outside=event=>{if(!root.value?.contains(event.target)){open.value=false;query.value=''}};onMounted(()=>document.addEventListener('pointerdown',outside));onBeforeUnmount(()=>document.removeEventListener('pointerdown',outside))
</script>
<template><div ref="root" class="custom-select" :class="{open}" @keydown="keydown"><span v-if="label" class="select-label">{{label}}</span><button type="button" class="trigger" :aria-expanded="open" aria-haspopup="listbox" @click="toggle"><span>{{selected?.label||placeholder}}</span><small v-if="selected?.meta">{{selected.meta}}</small><ChevronDown :size="15"/></button><div v-if="open" class="menu"><label v-if="searchable" class="select-search"><Search :size="14"/><input ref="searchInput" v-model="query" placeholder="Type to filter…" @keydown.stop="keydown"></label><div class="options" role="listbox"><button v-for="(option,index) in filtered" :key="option.value" type="button" role="option" :aria-selected="String(option.value)===String(modelValue)" :class="{active:index===active,selected:String(option.value)===String(modelValue)}" @mouseenter="active=index" @click="choose(option)"><span><b>{{option.label}}</b><small v-if="option.meta">{{option.meta}}</small></span><Check v-if="String(option.value)===String(modelValue)" :size="14"/></button><p v-if="!filtered.length">No matching options.</p></div></div></div></template>
<style scoped>.custom-select{position:relative;min-width:210px}.select-label{display:block;font:500 7px 'DM Mono';letter-spacing:.1em;color:var(--muted);text-transform:uppercase;margin-bottom:6px}.trigger{width:100%;height:44px;display:flex;align-items:center;gap:8px;padding:0 12px;border:1px solid var(--line);background:var(--surface);color:var(--text);text-align:left;cursor:pointer}.trigger>span{flex:0 0 auto;max-width:58%;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.trigger>small{min-width:0;margin-left:auto;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:7px 'DM Mono';color:var(--muted)}.trigger svg{flex:none;transition:.15s}.open .trigger{border-color:var(--ink)}.open .trigger svg{transform:rotate(180deg)}.menu{position:absolute;top:calc(100% + 5px);left:0;right:0;z-index:80;border:1px solid var(--ink);background:var(--surface);box-shadow:0 15px 40px rgba(20,22,18,.15)}.select-search{height:40px;display:flex;align-items:center;gap:8px;padding:0 10px;border-bottom:1px solid var(--line)}.select-search input{width:100%;border:0;outline:0;background:transparent;font-size:10px;color:var(--text)}.options{max-height:280px;overflow-y:auto;padding:4px}.options>button{width:100%;min-height:39px;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:7px 9px;border:0;background:transparent;color:var(--text);text-align:left;cursor:pointer}.options>button.active{background:var(--wash)}.options>button.selected{background:var(--ink);color:var(--paper)}.options span{display:flex;flex-direction:column}.options b{font-size:9px}.options small{font:7px 'DM Mono';color:var(--muted);margin-top:3px}.options>button.selected small{color:#9da198}.options p{padding:12px;margin:0;font-size:9px;color:var(--muted)}@media(max-width:600px){.custom-select{min-width:0;width:100%}.menu{position:fixed;left:13px;right:13px;top:auto;bottom:72px}.options{max-height:45vh}}</style>
