<script setup>
import{computed,nextTick,onBeforeUnmount,onMounted,ref}from'vue';import{Check,ChevronDown,Search}from'lucide-vue-next';import{AnimatePresence,motion,useReducedMotion}from'motion-v'
const props=defineProps({modelValue:[String,Number],options:{type:Array,default:()=>[]},placeholder:{type:String,default:'Select'},searchable:Boolean,label:String});const emit=defineEmits(['update:modelValue','change'])
const root=ref(),searchInput=ref(),open=ref(false),query=ref(''),active=ref(0),reduced=useReducedMotion()
const selected=computed(()=>props.options.find(option=>String(option.value)===String(props.modelValue)))
const filtered=computed(()=>{const term=query.value.toLowerCase().trim();return term?props.options.filter(option=>`${option.label} ${option.meta||''}`.toLowerCase().includes(term)):props.options})
const toggle=async()=>{open.value=!open.value;active.value=Math.max(0,filtered.value.findIndex(option=>String(option.value)===String(props.modelValue)));if(open.value&&props.searchable)await nextTick(()=>searchInput.value?.focus())}
const choose=option=>{emit('update:modelValue',option.value);emit('change',option.value);open.value=false;query.value=''}
const keydown=event=>{if(!open.value&&['ArrowDown','Enter',' '].includes(event.key)){event.preventDefault();toggle();return}if(!open.value)return;if(event.key==='Escape'){open.value=false;return}if(event.key==='ArrowDown'){event.preventDefault();active.value=Math.min(filtered.value.length-1,active.value+1)}if(event.key==='ArrowUp'){event.preventDefault();active.value=Math.max(0,active.value-1)}if(event.key==='Enter'&&filtered.value[active.value]){event.preventDefault();choose(filtered.value[active.value])}}
const outside=event=>{if(!root.value?.contains(event.target)){open.value=false;query.value=''}};onMounted(()=>document.addEventListener('pointerdown',outside));onBeforeUnmount(()=>document.removeEventListener('pointerdown',outside))
</script>
<template><div ref="root" class="custom-select" :class="{open}" @keydown="keydown"><span v-if="label" class="select-label">{{label}}</span><motion.button type="button" class="trigger" :aria-expanded="open" aria-haspopup="listbox" :while-hover="reduced?undefined:{y:-1}" :while-press="reduced?undefined:{scale:.985}" @click="toggle"><span>{{selected?.label||placeholder}}</span><small v-if="selected?.meta">{{selected.meta}}</small><ChevronDown :size="15"/></motion.button><AnimatePresence><motion.div v-if="open" class="menu" :initial="reduced?false:{opacity:0,y:-8,scale:.985}" :animate="{opacity:1,y:0,scale:1}" :exit="reduced?undefined:{opacity:0,y:-5,scale:.99}" :transition="{type:'spring',stiffness:420,damping:34}"><label v-if="searchable" class="select-search"><Search :size="14"/><input ref="searchInput" v-model="query" placeholder="Type to filter…" @keydown.stop="keydown"></label><div class="options" role="listbox"><motion.button v-for="(option,index) in filtered" :key="option.value" type="button" role="option" :aria-selected="String(option.value)===String(modelValue)" :class="{active:index===active,selected:String(option.value)===String(modelValue)}" :while-hover="reduced?undefined:{x:2}" :while-press="reduced?undefined:{scale:.99}" @mouseenter="active=index" @click="choose(option)"><span><b>{{option.label}}</b><small v-if="option.meta">{{option.meta}}</small></span><Check v-if="String(option.value)===String(modelValue)" :size="14"/></motion.button><p v-if="!filtered.length">No matching options.</p></div></motion.div></AnimatePresence></div></template>
<style scoped>.custom-select{position:relative;min-width:230px}.select-label{display:block;margin-bottom:8px;color:var(--muted);font:600 12px 'DM Mono';letter-spacing:.08em;text-transform:uppercase}.trigger{width:100%;min-height:48px;display:flex;align-items:center;gap:10px;padding:0 14px;border:1px solid var(--line);background:var(--surface);color:var(--text);text-align:left;cursor:pointer}.trigger>span{flex:1 1 auto;min-width:0;font-size:13px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.trigger>small{min-width:0;max-width:44%;margin-left:auto;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--muted);font:500 12px 'DM Mono'}.trigger svg{flex:none;transition:.2s var(--ease-emphasized)}.open .trigger{border-color:var(--accent);box-shadow:0 0 0 1px color-mix(in srgb,var(--accent) 35%,transparent)}.open .trigger svg{transform:rotate(180deg)}.menu{position:absolute;top:calc(100% + 7px);left:0;right:0;z-index:80;overflow:hidden;border:1px solid var(--line-strong);border-radius:10px;background:var(--surface);box-shadow:var(--shadow)}.select-search{min-height:46px;display:flex;align-items:center;gap:9px;padding:0 12px;border-bottom:1px solid var(--line)}.select-search input{width:100%;border:0;outline:0;background:transparent;color:var(--text);font-size:13px}.options{max-height:310px;overflow-y:auto;padding:6px}.options>button{width:100%;min-height:48px;display:flex;align-items:center;justify-content:space-between;gap:9px;padding:9px 11px;border:0;border-radius:7px;background:transparent;color:var(--text);text-align:left;cursor:pointer}.options>button.active{background:var(--wash)}.options>button.selected{background:var(--selection-bg);color:var(--selection-text)}.options span{display:flex;flex-direction:column}.options b{font-size:13px}.options small{margin-top:4px;color:var(--muted);font:500 12px 'DM Mono'}.options>button.selected small{color:color-mix(in srgb,var(--selection-text) 70%,transparent)}.options p{padding:14px;margin:0;color:var(--muted);font-size:13px}@media(max-width:600px){.custom-select{min-width:0;width:100%}.menu{position:fixed;left:13px;right:13px;top:auto;bottom:72px}.options{max-height:45vh}}</style>
